apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  annotations:
      {"apiVersion":"policy.karmada.io/v1alpha1","kind":"PropagationPolicy","metadata":{"annotations":{},"name":"volcano-global-dispatch-policy","namespace":"default"},"spec":{"conflictResolution":"Abort","placement":{"replicaScheduling":{"replicaDivisionPreference":"Aggregated","replicaSchedulingType":"Divided"}},"preemption":"Never","priority":0,"resourceSelectors":[{"apiVersion":"batch/v1","kind":"Job","labelSelector":{"matchLabels":{"volcano-global.io/dispatch":"true"}},"namespace":"default"},{"apiVersion":"batch.volcano.sh/v1alpha1","kind":"Job","labelSelector":{"matchLabels":{"volcano-global.io/dispatch":"true"}},"namespace":"default"}],"schedulerName":"default-scheduler"}}
  finalizers:
  - karmada.io/propagation-policy-controller
  labels:
    propagationpolicy.karmada.io/permanent-id: 1c7b1983-7b48-48bf-8eba-59a0d569c80d
  name: volcano-global-dispatch-policy
  namespace: default
spec:
  conflictResolution: Abort
  placement:
    replicaScheduling:
      replicaDivisionPreference: Aggregated
      replicaSchedulingType: Divided
  preemption: Never
  priority: 0
  resourceSelectors:
  - apiVersion: batch/v1
    kind: Job
    labelSelector:
      matchLabels:
        volcano-global.io/dispatch: "true"
    namespace: default
  - apiVersion: batch.volcano.sh/v1alpha1
    kind: Job
    labelSelector:
      matchLabels:
        volcano-global.io/dispatch: "true"
    namespace: default
  schedulerName: default-scheduler
