apiVersion: policy.karmada.io/v1alpha1
kind: ClusterPropagationPolicy
metadata:
  annotations:
      {"apiVersion":"policy.karmada.io/v1alpha1","kind":"ClusterPropagationPolicy","metadata":{"annotations":{},"name":"member2-secret-policy"},"spec":{"conflictResolution":"Abort","placement":{"clusterAffinity":{"clusterNames":["wlcb"]}},"priority":100,"resourceSelectors":[{"apiVersion":"v1","kind":"Secret","labelSelector":{"matchLabels":{"dispatch/member2":"true"}}}]}}
  finalizers:
  - karmada.io/cluster-propagation-policy-controller
  labels:
    clusterpropagationpolicy.karmada.io/permanent-id: 1f86c6d6-edb5-48c4-9024-b28ef44d1b50
    k8slens-edit-resource-version: v1alpha1
  name: member2-secret-policy
spec:
  conflictResolution: Abort
  placement:
    clusterAffinity:
      clusterNames:
      - wlcb
  preemption: Never
  priority: 100
  resourceSelectors:
  - apiVersion: v1
    kind: Secret
    labelSelector:
      matchLabels:
        dispatch/wlcb: "true"
  schedulerName: default-scheduler
