apiVersion: policy.karmada.io/v1alpha1
kind: ClusterPropagationPolicy
metadata:
  annotations:
      {"apiVersion":"policy.karmada.io/v1alpha1","kind":"ClusterPropagationPolicy","metadata":{"annotations":{},"name":"mindie-sd-namespace-propagation"},"spec":{"conflictResolution":"Overwrite","placement":{"clusterAffinity":{"clusterNames":["001","wlcb"]},"replicaScheduling":{"replicaSchedulingType":"Duplicated"}},"preemption":"Never","priority":0,"resourceSelectors":[{"apiVersion":"v1","kind":"Namespace","name":"mindie-sd"}],"schedulerName":"default-scheduler"}}
  finalizers:
  - karmada.io/cluster-propagation-policy-controller
  labels:
    clusterpropagationpolicy.karmada.io/permanent-id: 1035c6c5-40f1-4e0a-85ca-3652b722bc13
  name: mindie-sd-namespace-propagation
spec:
  conflictResolution: Overwrite
  placement:
    clusterAffinity:
      clusterNames:
      - "001"
      - wlcb
    replicaScheduling:
      replicaSchedulingType: Duplicated
  preemption: Never
  priority: 0
  resourceSelectors:
  - apiVersion: v1
    kind: Namespace
    name: mindie-sd
  schedulerName: default-scheduler
