apiVersion: policy.karmada.io/v1alpha1
kind: ClusterPropagationPolicy
metadata:
  annotations:
      {"apiVersion":"policy.karmada.io/v1alpha1","kind":"ClusterPropagationPolicy","metadata":{"annotations":{},"name":"multimodalsdk-namespace-propagation"},"spec":{"conflictResolution":"Overwrite","placement":{"clusterAffinity":{"clusterNames":["001","wlcb"]},"replicaScheduling":{"replicaSchedulingType":"Duplicated"}},"preemption":"Never","priority":0,"resourceSelectors":[{"apiVersion":"v1","kind":"Namespace","name":"MultimodalSDK"}],"schedulerName":"default-scheduler"}}
  finalizers:
  - karmada.io/cluster-propagation-policy-controller
  labels:
    clusterpropagationpolicy.karmada.io/permanent-id: a8e41a66-68f1-4153-aa1b-d575f200de26
  name: multimodalsdk-namespace-propagation
spec:
  conflictResolution: Overwrite
  placement:
    clusterAffinity:
      clusterNames:
      - "001"
      - wlcb
    replicaScheduling:
      replicaSchedulingType: Duplicated
  preemption: Never
  priority: 0
  resourceSelectors:
  - apiVersion: v1
    kind: Namespace
    name: multimodalsdk
  schedulerName: default-scheduler
