/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
If you want to view the source, please visit the GitHub repository.
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => OpenCodePlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian6 = require("obsidian");

// src/types.ts
var DEFAULT_SETTINGS = {
  port: 14096,
  hostname: "127.0.0.1",
  autoStart: false,
  opencodePath: "opencode",
  projectDirectory: "",
  startupTimeout: 45e3,
  defaultViewLocation: "sidebar",
  injectWorkspaceContext: false,
  maxNotesInContext: 20,
  maxSelectionLength: 2e3,
  customCommand: "",
  useCustomCommand: false
};
var OPENCODE_VIEW_TYPE = "opencode-view";

// src/ui/OpenCodeView.ts
var import_obsidian2 = require("obsidian");

// src/icons.ts
var import_obsidian = require("obsidian");
var OPENCODE_ICON_NAME = "opencode-logo";
var OPENCODE_LOGO_SVG = `<svg viewBox="0 0 24 30" fill="none" xmlns="http://www.w3.org/2000/svg">
  <path d="M18 24H6V12H18V24Z" fill="currentColor" opacity="0.4"/>
  <path d="M18 6H6V24H18V6ZM24 30H0V0H24V30Z" fill="currentColor"/>
</svg>`;
function registerOpenCodeIcons() {
  (0, import_obsidian.addIcon)(OPENCODE_ICON_NAME, OPENCODE_LOGO_SVG);
}

// src/ui/OpenCodeView.ts
var OpenCodeView = class extends import_obsidian2.ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    this.iframeEl = null;
    this.currentState = "stopped";
    this.unsubscribeStateChange = null;
    this.plugin = plugin;
  }
  getViewType() {
    return OPENCODE_VIEW_TYPE;
  }
  getDisplayText() {
    return "OpenCode";
  }
  getIcon() {
    return OPENCODE_ICON_NAME;
  }
  async onOpen() {
    this.contentEl.empty();
    this.contentEl.addClass("opencode-container");
    this.unsubscribeStateChange = this.plugin.onServerStateChange((state) => {
      this.currentState = state;
      this.updateView();
    });
    this.currentState = this.plugin.getServerState();
    this.updateView();
    if (this.currentState === "stopped") {
      this.plugin.startServer();
    }
  }
  async onClose() {
    if (this.unsubscribeStateChange) {
      this.unsubscribeStateChange();
      this.unsubscribeStateChange = null;
    }
    if (this.iframeEl) {
      const iframeUrl = this.iframeEl.src;
      if (iframeUrl.includes("/session/")) {
        this.plugin.setCachedIframeUrl(iframeUrl);
      }
      this.iframeEl.src = "about:blank";
      this.iframeEl = null;
    }
  }
  updateView() {
    switch (this.currentState) {
      case "stopped":
        this.renderStoppedState();
        break;
      case "starting":
        this.renderStartingState();
        break;
      case "running":
        this.renderRunningState();
        break;
      case "error":
        this.renderErrorState();
        break;
    }
  }
  renderStoppedState() {
    this.contentEl.empty();
    const statusContainer = this.contentEl.createDiv({
      cls: "opencode-status-container"
    });
    const iconEl = statusContainer.createDiv({ cls: "opencode-status-icon" });
    (0, import_obsidian2.setIcon)(iconEl, "power-off");
    statusContainer.createEl("h3", { text: "OpenCode is stopped" });
    statusContainer.createEl("p", {
      text: "Click the button below to start the OpenCode server.",
      cls: "opencode-status-message"
    });
    const startButton = statusContainer.createEl("button", {
      text: "Start OpenCode",
      cls: "mod-cta"
    });
    startButton.addEventListener("click", () => {
      this.plugin.startServer();
    });
  }
  renderStartingState() {
    this.contentEl.empty();
    const statusContainer = this.contentEl.createDiv({
      cls: "opencode-status-container"
    });
    const loadingEl = statusContainer.createDiv({ cls: "opencode-loading" });
    loadingEl.createDiv({ cls: "opencode-spinner" });
    statusContainer.createEl("h3", { text: "Starting OpenCode..." });
    statusContainer.createEl("p", {
      text: "Please wait while the server starts up.",
      cls: "opencode-status-message"
    });
  }
  renderRunningState() {
    var _a;
    this.contentEl.empty();
    const headerEl = this.contentEl.createDiv({ cls: "opencode-header" });
    const titleSection = headerEl.createDiv({ cls: "opencode-header-title" });
    const iconEl = titleSection.createSpan();
    (0, import_obsidian2.setIcon)(iconEl, OPENCODE_ICON_NAME);
    titleSection.createSpan({ text: "OpenCode" });
    const actionsEl = headerEl.createDiv({ cls: "opencode-header-actions" });
    const reloadButton = actionsEl.createEl("button", {
      attr: { "aria-label": "Reload" }
    });
    (0, import_obsidian2.setIcon)(reloadButton, "refresh-cw");
    reloadButton.addEventListener("click", () => {
      this.reloadIframe();
    });
    const stopButton = actionsEl.createEl("button", {
      attr: { "aria-label": "Stop server" }
    });
    (0, import_obsidian2.setIcon)(stopButton, "square");
    stopButton.addEventListener("click", () => {
      this.plugin.stopServer();
    });
    const iframeContainer = this.contentEl.createDiv({
      cls: "opencode-iframe-container"
    });
    const iframeUrl = (_a = this.plugin.getStoredIframeUrl()) != null ? _a : this.plugin.getServerUrl();
    console.log("[OpenCode] Loading iframe with URL:", iframeUrl);
    this.iframeEl = iframeContainer.createEl("iframe", {
      cls: "opencode-iframe",
      attr: {
        src: iframeUrl,
        frameborder: "0",
        allow: "clipboard-read; clipboard-write"
      }
    });
    this.iframeEl.addEventListener("error", () => {
      console.error("Failed to load OpenCode iframe");
    });
    this.iframeEl.addEventListener("focus", () => {
      this.plugin.refreshContextForView(this);
    });
    this.iframeEl.addEventListener("pointerdown", () => {
      this.plugin.refreshContextForView(this);
    });
    void this.plugin.ensureSessionUrl(this);
  }
  getIframeUrl() {
    var _a, _b;
    return (_b = (_a = this.iframeEl) == null ? void 0 : _a.src) != null ? _b : null;
  }
  setIframeUrl(url) {
    if (this.iframeEl && this.iframeEl.src !== url) {
      this.iframeEl.src = url;
    }
  }
  renderErrorState() {
    this.contentEl.empty();
    const statusContainer = this.contentEl.createDiv({
      cls: "opencode-status-container opencode-error"
    });
    const iconEl = statusContainer.createDiv({ cls: "opencode-status-icon" });
    (0, import_obsidian2.setIcon)(iconEl, "alert-circle");
    statusContainer.createEl("h3", { text: "Failed to start OpenCode" });
    const errorMessage = this.plugin.getLastError();
    if (errorMessage) {
      statusContainer.createEl("p", {
        text: errorMessage,
        cls: "opencode-status-message opencode-error-message"
      });
    } else {
      statusContainer.createEl("p", {
        text: "There was an error starting the OpenCode server.",
        cls: "opencode-status-message"
      });
    }
    const buttonContainer = statusContainer.createDiv({
      cls: "opencode-button-group"
    });
    const retryButton = buttonContainer.createEl("button", {
      text: "Retry",
      cls: "mod-cta"
    });
    retryButton.addEventListener("click", () => {
      this.plugin.startServer();
    });
    const settingsButton = buttonContainer.createEl("button", {
      text: "Open Settings"
    });
    settingsButton.addEventListener("click", () => {
      this.app.setting.open();
      this.app.setting.openTabById("obsidian-opencode");
    });
  }
  reloadIframe() {
    if (this.iframeEl) {
      const src = this.iframeEl.src;
      this.iframeEl.src = "about:blank";
      setTimeout(() => {
        if (this.iframeEl) {
          this.iframeEl.src = src;
        }
      }, 100);
    }
  }
};

// src/ui/ViewManager.ts
var ViewManager = class {
  constructor(deps) {
    this.app = deps.app;
    this.settings = deps.settings;
    this.client = deps.client;
    this.contextManager = deps.contextManager;
    this.getCachedIframeUrl = deps.getCachedIframeUrl;
    this.setCachedIframeUrl = deps.setCachedIframeUrl;
    this.getServerState = deps.getServerState;
  }
  updateSettings(settings) {
    this.settings = settings;
  }
  getExistingLeaf() {
    const leaves = this.app.workspace.getLeavesOfType(OPENCODE_VIEW_TYPE);
    return leaves.length > 0 ? leaves[0] : null;
  }
  async activateView() {
    const existingLeaf = this.getExistingLeaf();
    if (existingLeaf) {
      this.app.workspace.revealLeaf(existingLeaf);
      return;
    }
    let leaf = null;
    if (this.settings.defaultViewLocation === "main") {
      leaf = this.app.workspace.getLeaf("tab");
    } else {
      leaf = this.app.workspace.getRightLeaf(false);
    }
    if (leaf) {
      await leaf.setViewState({
        type: OPENCODE_VIEW_TYPE,
        active: true
      });
      this.app.workspace.revealLeaf(leaf);
    }
  }
  async toggleView() {
    const existingLeaf = this.getExistingLeaf();
    if (existingLeaf) {
      const isInSidebar = existingLeaf.getRoot() === this.app.workspace.rightSplit;
      if (isInSidebar) {
        const rightSplit = this.app.workspace.rightSplit;
        if (rightSplit && !rightSplit.collapsed) {
          existingLeaf.detach();
        } else {
          this.app.workspace.revealLeaf(existingLeaf);
        }
      } else {
        existingLeaf.detach();
      }
    } else {
      await this.activateView();
    }
  }
  async ensureSessionUrl(view) {
    if (this.getServerState() !== "running") {
      return;
    }
    const cachedUrl = this.getCachedIframeUrl();
    const existingUrl = cachedUrl != null ? cachedUrl : view.getIframeUrl();
    if (existingUrl && this.client.resolveSessionId(existingUrl)) {
      this.setCachedIframeUrl(existingUrl);
      return;
    }
    const sessionId = await this.client.createSession();
    if (!sessionId) {
      return;
    }
    const sessionUrl = this.client.getSessionUrl(sessionId);
    this.setCachedIframeUrl(sessionUrl);
    view.setIframeUrl(sessionUrl);
    if (this.app.workspace.activeLeaf === view.leaf) {
      await this.contextManager.refreshContextForView(view);
    }
  }
};

// src/settings/SettingsTab.ts
var import_obsidian3 = require("obsidian");
var import_fs2 = require("fs");
var import_os2 = require("os");

// src/server/ExecutableResolver.ts
var import_fs = require("fs");
var import_os = require("os");
var import_path = require("path");
var import_child_process = require("child_process");
var ExecutableResolver = class {
  /**
   * Resolve the executable path based on configuration and platform
   * @param configuredPath The path configured in settings (e.g., "opencode" or "/path/to/opencode")
   * @returns The resolved full path or the configured path as fallback
   */
  static resolve(configuredPath) {
    if ((0, import_path.isAbsolute)(configuredPath) && (0, import_fs.existsSync)(configuredPath)) {
      return configuredPath;
    }
    const execName = (0, import_path.basename)(configuredPath) || configuredPath;
    const searchDirs = this.getSearchDirectories();
    for (const dir of searchDirs) {
      const fullPath = (0, import_path.join)(dir, execName);
      if ((0, import_fs.existsSync)(fullPath)) {
        console.log("[OpenCode] Found executable at:", fullPath);
        return fullPath;
      }
    }
    console.log("[OpenCode] Executable not found in common paths, using configured:", configuredPath);
    return configuredPath;
  }
  /**
   * Check if executable exists in PATH
   * @param execName Name of executable to search for
   * @returns Full path if found in PATH, null otherwise
   */
  static resolveFromPath(execName) {
    try {
      const command = (0, import_os.platform)() === "win32" ? "where" : "which";
      const result = (0, import_child_process.execSync)(`${command} "${execName}"`, { encoding: "utf-8", stdio: ["pipe", "pipe", "ignore"] });
      const path = result.trim().split("\n")[0];
      if (path && (0, import_fs.existsSync)(path)) {
        return path;
      }
    } catch (e) {
    }
    return null;
  }
  /**
   * Get platform-specific directories to search for executables
   */
  static getSearchDirectories() {
    const currentPlatform = (0, import_os.platform)();
    const homeDir = (0, import_os.homedir)();
    const searchDirs = [];
    if (currentPlatform === "linux" || currentPlatform === "darwin") {
      searchDirs.push(
        (0, import_path.join)(homeDir, ".local", "bin"),
        (0, import_path.join)(homeDir, ".opencode", "bin"),
        (0, import_path.join)(homeDir, ".bun", "bin"),
        (0, import_path.join)(homeDir, ".npm-global", "bin")
      );
      const nvmDirs = this.expandNvmDirectories(homeDir);
      searchDirs.push(...nvmDirs);
      searchDirs.push("/usr/local/bin", "/usr/bin");
      if (currentPlatform === "darwin") {
        searchDirs.push("/opt/homebrew/bin");
      }
    } else if (currentPlatform === "win32") {
      const localAppData = process.env.LOCALAPPDATA || (0, import_path.join)(homeDir, "AppData", "Local");
      const userProfile = process.env.USERPROFILE || homeDir;
      searchDirs.push(
        (0, import_path.join)(localAppData, "opencode", "bin"),
        (0, import_path.join)(userProfile, ".bun", "bin"),
        (0, import_path.join)(userProfile, ".local", "bin")
      );
    }
    return searchDirs;
  }
  /**
   * Expand nvm wildcard directories
   * Searches ~/.nvm/versions/node/ for installed versions
   */
  static expandNvmDirectories(homeDir) {
    const nvmBaseDir = (0, import_path.join)(homeDir, ".nvm", "versions", "node");
    const nvmDirs = [];
    try {
      if ((0, import_fs.existsSync)(nvmBaseDir)) {
        const { readdirSync } = require("fs");
        const versions = readdirSync(nvmBaseDir, { withFileTypes: true });
        for (const version of versions) {
          if (version.isDirectory()) {
            nvmDirs.push((0, import_path.join)(nvmBaseDir, version.name, "bin"));
          }
        }
      }
    } catch (e) {
    }
    return nvmDirs;
  }
};

// src/settings/SettingsTab.ts
function expandTilde(path) {
  if (path === "~") {
    return (0, import_os2.homedir)();
  }
  if (path.startsWith("~/")) {
    return path.replace("~", (0, import_os2.homedir)());
  }
  return path;
}
var OpenCodeSettingTab = class extends import_obsidian3.PluginSettingTab {
  constructor(app, plugin, settings, serverManager, onSettingsChange) {
    super(app, plugin);
    this.settings = settings;
    this.serverManager = serverManager;
    this.onSettingsChange = onSettingsChange;
    this.validateTimeout = null;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "OpenCode Settings" });
    containerEl.createEl("h3", { text: "Server Configuration" });
    new import_obsidian3.Setting(containerEl).setName("Port").setDesc("Port number for the OpenCode web server").addText(
      (text) => text.setPlaceholder("14096").setValue(this.settings.port.toString()).onChange(async (value) => {
        const port = parseInt(value, 10);
        if (!isNaN(port) && port > 0 && port < 65536) {
          this.settings.port = port;
          await this.onSettingsChange();
        }
      })
    );
    new import_obsidian3.Setting(containerEl).setName("Hostname").setDesc("Hostname to bind the server to (usually 127.0.0.1)").addText(
      (text) => text.setPlaceholder("127.0.0.1").setValue(this.settings.hostname).onChange(async (value) => {
        this.settings.hostname = value || "127.0.0.1";
        await this.onSettingsChange();
      })
    );
    const customCmdSetting = new import_obsidian3.Setting(containerEl).setName("Use custom command").setDesc("Enable to use a custom shell command instead of the executable path").addToggle(
      (toggle) => toggle.setValue(this.settings.useCustomCommand).onChange(async (value) => {
        this.settings.useCustomCommand = value;
        await this.onSettingsChange();
        this.display();
      })
    );
    const descEl = customCmdSetting.descEl;
    descEl.createEl("br");
    const linkEl = descEl.createEl("a", {
      text: "Learn more",
      href: "https://github.com/mtymek/opencode-obsidian#custom-command-mode"
    });
    linkEl.addEventListener("click", (e) => {
      e.preventDefault();
      window.open(linkEl.href, "_blank");
    });
    if (this.settings.useCustomCommand) {
      new import_obsidian3.Setting(containerEl).setName("Custom command").setDesc("Custom shell command to start OpenCode.").addTextArea((text) => {
        text.setPlaceholder("opencode serve --port 14096 --hostname 127.0.0.1 --cors app://obsidian.md").setValue(this.settings.customCommand).onChange(async (value) => {
          this.settings.customCommand = value;
          await this.onSettingsChange();
        });
        text.inputEl.rows = 3;
        text.inputEl.style.width = "100%";
        return text;
      });
    } else {
      const pathSetting = new import_obsidian3.Setting(containerEl).setName("OpenCode executable path").addText(
        (text) => text.setPlaceholder("opencode").setValue(this.settings.opencodePath).onChange(async (value) => {
          this.settings.opencodePath = value;
          await this.onSettingsChange();
        })
      );
      pathSetting.addButton((button) => {
        button.setButtonText("Autodetect").onClick(async () => {
          const detectedPath = ExecutableResolver.resolve("opencode");
          if (detectedPath && detectedPath !== "opencode") {
            this.settings.opencodePath = detectedPath;
            await this.onSettingsChange();
            this.display();
            new import_obsidian3.Notice(`OpenCode executable found at ${detectedPath}`);
          } else {
            new import_obsidian3.Notice("Could not find opencode. Please check your installation.");
          }
        });
      });
    }
    new import_obsidian3.Setting(containerEl).setName("Project directory").setDesc(
      "Override the starting directory for OpenCode. Leave empty to use the vault root."
    ).addText(
      (text) => text.setPlaceholder("/path/to/project or ~/project").setValue(this.settings.projectDirectory).onChange((value) => {
        if (this.validateTimeout) {
          clearTimeout(this.validateTimeout);
        }
        this.validateTimeout = setTimeout(async () => {
          await this.validateAndSetProjectDirectory(value);
        }, 500);
      })
    );
    containerEl.createEl("h3", { text: "Behavior" });
    new import_obsidian3.Setting(containerEl).setName("Auto-start server").setDesc(
      "Automatically start the OpenCode server when Obsidian opens (not recommended for faster startup)"
    ).addToggle(
      (toggle) => toggle.setValue(this.settings.autoStart).onChange(async (value) => {
        this.settings.autoStart = value;
        await this.onSettingsChange();
      })
    );
    new import_obsidian3.Setting(containerEl).setName("Default view location").setDesc(
      "Where to open the OpenCode panel: sidebar opens in the right panel, main opens as a tab in the editor area"
    ).addDropdown(
      (dropdown) => dropdown.addOption("sidebar", "Sidebar").addOption("main", "Main window").setValue(this.settings.defaultViewLocation).onChange(async (value) => {
        this.settings.defaultViewLocation = value;
        await this.onSettingsChange();
      })
    );
    containerEl.createEl("h3", { text: "Workspace Context" });
    new import_obsidian3.Setting(containerEl).setName("Inject workspace context").setDesc(
      "Includes open note paths and selected text in OpenCode when the view is focused"
    ).addToggle(
      (toggle) => toggle.setValue(this.settings.injectWorkspaceContext).onChange(async (value) => {
        this.settings.injectWorkspaceContext = value;
        await this.onSettingsChange();
      })
    );
    new import_obsidian3.Setting(containerEl).setName("Max notes in context").setDesc("Limit how many open notes are included").addSlider(
      (slider) => slider.setLimits(1, 50, 1).setValue(this.settings.maxNotesInContext).setDynamicTooltip().onChange(async (value) => {
        this.settings.maxNotesInContext = value;
        await this.onSettingsChange();
      })
    );
    new import_obsidian3.Setting(containerEl).setName("Max selection length").setDesc("Truncate selected text to avoid oversized context").addSlider(
      (slider) => slider.setLimits(500, 5e3, 100).setValue(this.settings.maxSelectionLength).setDynamicTooltip().onChange(async (value) => {
        this.settings.maxSelectionLength = value;
        await this.onSettingsChange();
      })
    );
    containerEl.createEl("h3", { text: "Server Status" });
    const statusContainer = containerEl.createDiv({ cls: "opencode-settings-status" });
    this.renderServerStatus(statusContainer);
  }
  async validateAndSetProjectDirectory(value) {
    const trimmed = value.trim();
    if (!trimmed) {
      this.serverManager.updateProjectDirectory("");
      await this.onSettingsChange();
      return;
    }
    if (!trimmed.startsWith("/") && !trimmed.startsWith("~") && !trimmed.match(/^[A-Za-z]:\\/)) {
      new import_obsidian3.Notice("Project directory must be an absolute path (or start with ~)");
      return;
    }
    const expanded = expandTilde(trimmed);
    try {
      if (!(0, import_fs2.existsSync)(expanded)) {
        new import_obsidian3.Notice("Project directory does not exist");
        return;
      }
      const stat = (0, import_fs2.statSync)(expanded);
      if (!stat.isDirectory()) {
        new import_obsidian3.Notice("Project directory path is not a directory");
        return;
      }
    } catch (error) {
      new import_obsidian3.Notice(`Failed to validate path: ${error.message}`);
      return;
    }
    this.serverManager.updateProjectDirectory(expanded);
    await this.onSettingsChange();
  }
  renderServerStatus(container) {
    container.empty();
    const state = this.serverManager.getState();
    const statusText = {
      stopped: "Stopped",
      starting: "Starting...",
      running: "Running",
      error: "Error"
    };
    const statusClass = {
      stopped: "status-stopped",
      starting: "status-starting",
      running: "status-running",
      error: "status-error"
    };
    const statusEl = container.createDiv({ cls: "opencode-status-line" });
    statusEl.createSpan({ text: "Status: " });
    statusEl.createSpan({
      text: statusText[state],
      cls: `opencode-status-badge ${statusClass[state]}`
    });
    if (state === "error") {
      const errorMsg = this.serverManager.getLastError();
      if (errorMsg) {
        const errorEl = container.createDiv({ cls: "opencode-error-details" });
        errorEl.createEl("div", {
          text: errorMsg,
          cls: "opencode-error-text"
        });
      }
    }
    if (state === "running") {
      const urlEl = container.createDiv({ cls: "opencode-status-line" });
      urlEl.createSpan({ text: "URL: " });
      const serverUrl = this.serverManager.getUrl();
      const linkEl = urlEl.createEl("a", {
        text: serverUrl,
        href: serverUrl
      });
      linkEl.addEventListener("click", (e) => {
        e.preventDefault();
        window.open(serverUrl, "_blank");
      });
    }
    const buttonContainer = container.createDiv({ cls: "opencode-settings-buttons" });
    if (state === "stopped" || state === "error") {
      const startButton = buttonContainer.createEl("button", {
        text: "Start Server",
        cls: "mod-cta"
      });
      startButton.addEventListener("click", async () => {
        await this.serverManager.start();
        this.renderServerStatus(container);
      });
    }
    if (state === "running") {
      const stopButton = buttonContainer.createEl("button", {
        text: "Stop Server"
      });
      stopButton.addEventListener("click", () => {
        this.serverManager.stop();
        this.renderServerStatus(container);
      });
      const restartButton = buttonContainer.createEl("button", {
        text: "Restart Server",
        cls: "mod-warning"
      });
      restartButton.addEventListener("click", async () => {
        this.serverManager.stop();
        await this.serverManager.start();
        this.renderServerStatus(container);
      });
    }
    if (state === "starting") {
      buttonContainer.createSpan({
        text: "Please wait...",
        cls: "opencode-status-waiting"
      });
    }
  }
};

// src/server/ServerManager.ts
var import_events = require("events");

// src/server/process/WindowsProcess.ts
var import_child_process2 = require("child_process");
var _WindowsProcess = class _WindowsProcess {
  start(command, args, options) {
    const process2 = (0, import_child_process2.spawn)(command, args, {
      ...options,
      shell: true,
      windowsHide: true
    });
    _WindowsProcess.currentProcess = process2;
    _WindowsProcess.registerCleanupHandler();
    return process2;
  }
  async stop(process2) {
    const pid = process2.pid;
    if (!pid) {
      _WindowsProcess.currentProcess = null;
      return;
    }
    console.log("[OpenCode] Stopping server process tree, PID:", pid);
    try {
      const { execSync: execSync2 } = require("child_process");
      const output = execSync2(
        `powershell -Command "Get-CimInstance Win32_Process -Filter \\"ParentProcessId=${pid}\\" | Select-Object ProcessId"`,
        { encoding: "utf8", stdio: ["pipe", "pipe", "ignore"] }
      );
      const lines = output.split("\n").slice(3);
      for (const line of lines) {
        const childPid = line.trim();
        if (childPid && !isNaN(parseInt(childPid))) {
          try {
            execSync2(`taskkill /F /PID ${childPid}`, { stdio: "ignore" });
          } catch (e) {
          }
        }
      }
    } catch (e) {
    }
    try {
      await this.execAsync(`taskkill /F /PID ${pid}`);
    } catch (e) {
    }
    _WindowsProcess.currentProcess = null;
    await this.waitForExit(process2, 5e3);
  }
  static registerCleanupHandler() {
    if (_WindowsProcess.cleanupHandlerRegistered) {
      return;
    }
    if (typeof window !== "undefined" && !process.env.CI) {
      window.addEventListener("beforeunload", () => {
        var _a;
        if ((_a = _WindowsProcess.currentProcess) == null ? void 0 : _a.pid) {
          _WindowsProcess.killProcessSync(_WindowsProcess.currentProcess.pid);
        }
      });
      _WindowsProcess.cleanupHandlerRegistered = true;
    }
  }
  static killProcessSync(pid) {
    try {
      const { execSync: execSync2 } = require("child_process");
      try {
        const output = execSync2(
          `powershell -Command "Get-CimInstance Win32_Process -Filter \\"ParentProcessId=${pid}\\" | Select-Object ProcessId"`,
          { encoding: "utf8", stdio: ["pipe", "pipe", "ignore"] }
        );
        const lines = output.split("\n").slice(3);
        for (const line of lines) {
          const childPid = line.trim();
          if (childPid && !isNaN(parseInt(childPid))) {
            try {
              execSync2(`taskkill /F /PID ${childPid}`, { stdio: "ignore" });
            } catch (e) {
            }
          }
        }
      } catch (e) {
      }
      try {
        execSync2(`taskkill /F /PID ${pid}`, { stdio: "ignore" });
      } catch (e) {
      }
    } catch (e) {
    }
  }
  async verifyCommand(command) {
    try {
      await this.execAsync(`where "${command}"`);
      return null;
    } catch (e) {
      return `Executable not found at '${command}'. Check Settings \u2192 OpenCode path, or click "Autodetect"`;
    }
  }
  async waitForExit(process2, timeoutMs) {
    if (process2.exitCode !== null || process2.signalCode !== null) {
      return;
    }
    return new Promise((resolve) => {
      const timeout = setTimeout(() => {
        cleanup();
        resolve();
      }, timeoutMs);
      const onExit = () => {
        cleanup();
        resolve();
      };
      const cleanup = () => {
        clearTimeout(timeout);
        process2.off("exit", onExit);
        process2.off("error", onExit);
      };
      process2.once("exit", onExit);
      process2.once("error", onExit);
    });
  }
  execAsync(command) {
    return new Promise((resolve, reject) => {
      const { exec } = require("child_process");
      exec(command, (error) => {
        if (error) {
          reject(error);
        } else {
          resolve();
        }
      });
    });
  }
};
// Static state to track the current process for cleanup
_WindowsProcess.currentProcess = null;
_WindowsProcess.cleanupHandlerRegistered = false;
var WindowsProcess = _WindowsProcess;

// src/server/process/PosixProcess.ts
var import_child_process3 = require("child_process");
var import_fs3 = require("fs");
var PosixProcess = class {
  start(command, args, options) {
    return (0, import_child_process3.spawn)(command, args, {
      ...options,
      detached: true
      // Creates a new process group
    });
  }
  async stop(process2) {
    const pid = process2.pid;
    if (!pid) {
      return;
    }
    console.log("[OpenCode] Stopping server process tree, PID:", pid);
    await this.killProcessGroup(pid, "SIGTERM");
    const gracefulExited = await this.waitForExit(process2, 2e3);
    if (gracefulExited) {
      console.log("[OpenCode] Server stopped gracefully");
      return;
    }
    console.log("[OpenCode] Process didn't exit gracefully, sending SIGKILL");
    await this.killProcessGroup(pid, "SIGKILL");
    const forceExited = await this.waitForExit(process2, 3e3);
    if (forceExited) {
      console.log("[OpenCode] Server stopped with SIGKILL");
    } else {
      console.error("[OpenCode] Failed to stop server within timeout");
    }
  }
  async verifyCommand(command) {
    if (command.startsWith("/") || command.startsWith("./")) {
      const fs = require("fs");
      try {
        fs.accessSync(command, fs.constants.X_OK);
        return null;
      } catch (err) {
        if ((0, import_fs3.existsSync)(command)) {
          return `'${command}' exists but is not executable. Run: chmod +x ${command}`;
        }
        return `Executable not found at '${command}'. Check Settings \u2192 OpenCode path, or click "Autodetect"`;
      }
    }
    return null;
  }
  async killProcessGroup(pid, signal) {
    try {
      process.kill(-pid, signal);
    } catch (error) {
      console.log(`[OpenCode] Signal ${signal} failed (process may already be gone)`);
    }
  }
  async waitForExit(process2, timeoutMs) {
    if (process2.exitCode !== null || process2.signalCode !== null) {
      return true;
    }
    return new Promise((resolve) => {
      const timeout = setTimeout(() => {
        cleanup();
        resolve(false);
      }, timeoutMs);
      const onExit = () => {
        cleanup();
        resolve(true);
      };
      const cleanup = () => {
        clearTimeout(timeout);
        process2.off("exit", onExit);
        process2.off("error", onExit);
      };
      process2.once("exit", onExit);
      process2.once("error", onExit);
    });
  }
};

// src/server/ServerManager.ts
var ServerManager = class extends import_events.EventEmitter {
  constructor(settings, projectDirectory) {
    super();
    this.process = null;
    this.state = "stopped";
    this.lastError = null;
    this.earlyExitCode = null;
    this.settings = settings;
    this.projectDirectory = projectDirectory;
    this.processImpl = process.platform === "win32" ? new WindowsProcess() : new PosixProcess();
  }
  updateSettings(settings) {
    this.settings = settings;
  }
  updateProjectDirectory(directory) {
    this.projectDirectory = directory;
    this.emit("projectDirectoryChanged", directory);
  }
  getState() {
    return this.state;
  }
  getLastError() {
    return this.lastError;
  }
  getUrl() {
    const encodedPath = Buffer.from(this.projectDirectory).toString("base64");
    return `http://${this.settings.hostname}:${this.settings.port}/${encodedPath}`;
  }
  async start() {
    var _a, _b;
    if (this.state === "running" || this.state === "starting") {
      return true;
    }
    this.setState("starting");
    this.lastError = null;
    this.earlyExitCode = null;
    if (!this.projectDirectory) {
      return this.setError("Project directory (vault) not configured");
    }
    let executablePath;
    let spawnOptions;
    if (this.settings.useCustomCommand) {
      executablePath = this.settings.customCommand;
      spawnOptions = {
        cwd: this.projectDirectory,
        env: { ...process.env, NODE_USE_SYSTEM_CA: "1" },
        stdio: ["ignore", "pipe", "pipe"],
        shell: true
      };
    } else {
      executablePath = ExecutableResolver.resolve(this.settings.opencodePath);
      const commandError = await this.processImpl.verifyCommand(executablePath);
      if (commandError) {
        return this.setError(commandError);
      }
      spawnOptions = {
        cwd: this.projectDirectory,
        env: { ...process.env, NODE_USE_SYSTEM_CA: "1" },
        stdio: ["ignore", "pipe", "pipe"]
      };
    }
    if (await this.checkServerHealth()) {
      console.log(
        "[OpenCode] Server already running on port",
        this.settings.port
      );
      this.setState("running");
      return true;
    }
    console.log("[OpenCode] Starting server:", {
      mode: this.settings.useCustomCommand ? "custom" : "path",
      command: executablePath,
      port: this.settings.port,
      hostname: this.settings.hostname,
      cwd: this.projectDirectory,
      projectDirectory: this.projectDirectory
    });
    if (this.settings.useCustomCommand) {
      this.process = this.processImpl.start(
        executablePath,
        [],
        // User controls all arguments in custom command
        spawnOptions
      );
    } else {
      this.process = this.processImpl.start(
        executablePath,
        [
          "serve",
          "--port",
          this.settings.port.toString(),
          "--hostname",
          this.settings.hostname,
          "--cors",
          "app://obsidian.md"
        ],
        spawnOptions
      );
    }
    console.log("[OpenCode] Process spawned with PID:", this.process.pid);
    (_a = this.process.stdout) == null ? void 0 : _a.on("data", (data) => {
      console.log("[OpenCode]", data.toString().trim());
    });
    (_b = this.process.stderr) == null ? void 0 : _b.on("data", (data) => {
      console.error("[OpenCode Error]", data.toString().trim());
    });
    this.process.on("exit", (code, signal) => {
      console.log(
        `[OpenCode] Process exited with code ${code}, signal ${signal}`
      );
      this.process = null;
      if (this.state === "starting" && code !== null && code !== 0) {
        this.earlyExitCode = code;
      }
      if (this.state === "running") {
        this.setState("stopped");
      }
    });
    this.process.on("error", (err) => {
      console.error("[OpenCode] Failed to start process:", err);
      this.process = null;
      if (err.code === "ENOENT") {
        const command = this.settings.useCustomCommand ? this.settings.customCommand : this.settings.opencodePath;
        this.setError(
          `Executable not found: '${command}'`
        );
      } else {
        this.setError(`Failed to start: ${err.message}`);
      }
    });
    const ready = await this.waitForServerOrExit(this.settings.startupTimeout);
    if (ready) {
      this.setState("running");
      return true;
    }
    if (this.state === "error") {
      return false;
    }
    await this.stop();
    if (this.earlyExitCode !== null) {
      return this.setError(
        `Process exited unexpectedly (exit code ${this.earlyExitCode})`
      );
    }
    if (!this.process) {
      return this.setError("Process exited before server became ready");
    }
    return this.setError("Server failed to start within timeout");
  }
  async stop() {
    if (!this.process) {
      this.setState("stopped");
      return;
    }
    const proc = this.process;
    this.setState("stopped");
    this.process = null;
    await this.processImpl.stop(proc);
  }
  setState(state) {
    this.state = state;
    this.emit("stateChange", state);
  }
  setError(message) {
    this.lastError = message;
    console.error("[OpenCode Error]", message);
    this.setState("error");
    return false;
  }
  async checkServerHealth() {
    try {
      const response = await fetch(`${this.getUrl()}/global/health`, {
        method: "GET",
        signal: AbortSignal.timeout(2e3)
      });
      return response.ok;
    } catch (e) {
      return false;
    }
  }
  async waitForServerOrExit(timeoutMs) {
    const startTime = Date.now();
    const pollInterval = 500;
    while (Date.now() - startTime < timeoutMs) {
      if (!this.process) {
        console.log("[OpenCode] Process exited before server became ready");
        return false;
      }
      if (await this.checkServerHealth()) {
        return true;
      }
      await this.sleep(pollInterval);
    }
    return false;
  }
  sleep(ms) {
    return new Promise((resolve) => setTimeout(resolve, ms));
  }
};

// src/client/OpenCodeClient.ts
var OpenCodeClient = class {
  constructor(apiBaseUrl, uiBaseUrl, projectDirectory) {
    this.trackedSessionId = null;
    this.lastPart = null;
    this.apiBaseUrl = this.normalizeBaseUrl(apiBaseUrl);
    this.uiBaseUrl = this.normalizeBaseUrl(uiBaseUrl);
    this.projectDirectory = projectDirectory;
  }
  updateBaseUrl(apiBaseUrl, uiBaseUrl, projectDirectory) {
    const nextApiUrl = this.normalizeBaseUrl(apiBaseUrl);
    const nextUiUrl = this.normalizeBaseUrl(uiBaseUrl);
    if (nextApiUrl !== this.apiBaseUrl || nextUiUrl !== this.uiBaseUrl || projectDirectory !== this.projectDirectory) {
      this.apiBaseUrl = nextApiUrl;
      this.uiBaseUrl = nextUiUrl;
      this.projectDirectory = projectDirectory;
      this.resetTracking();
    }
  }
  resetTracking() {
    this.trackedSessionId = null;
    this.lastPart = null;
  }
  getSessionUrl(sessionId) {
    return `${this.uiBaseUrl}/session/${sessionId}`;
  }
  resolveSessionId(iframeUrl) {
    var _a;
    const match = iframeUrl.match(/\/session\/([^/?#]+)/);
    return (_a = match == null ? void 0 : match[1]) != null ? _a : null;
  }
  async createSession() {
    var _a;
    const result = await this.request("POST", "/session", {
      title: "Obsidian"
    });
    const session = this.unwrap(result);
    return (_a = session == null ? void 0 : session.id) != null ? _a : null;
  }
  async updateContext(params) {
    var _a, _b, _c;
    const { sessionId, contextText } = params;
    if (this.trackedSessionId && this.trackedSessionId !== sessionId) {
      this.resetTracking();
    }
    this.trackedSessionId = sessionId;
    if (!contextText) {
      await this.ignorePreviousPart();
      return;
    }
    if (this.lastPart) {
      const updated = await this.updatePart(this.lastPart, { text: contextText });
      if (updated) {
        return;
      }
      await this.ignorePreviousPart();
    }
    const message = await this.sendPrompt(sessionId, contextText);
    if ((_a = message == null ? void 0 : message.info) == null ? void 0 : _a.id) {
      this.lastPart = (_c = (_b = message.parts) == null ? void 0 : _b[0]) != null ? _c : null;
    }
  }
  async sendPrompt(sessionId, contextText) {
    const result = await this.request(
      "POST",
      `/session/${sessionId}/message`,
      {
        noReply: true,
        parts: [{ type: "text", text: contextText }]
      }
    );
    console.log("[OpenCode] Injected context message");
    console.log(contextText);
    const message = this.unwrap(result);
    if (!message) {
      console.error("[OpenCode] Failed to inject context message");
    }
    return message;
  }
  async updatePart(part, updates) {
    const result = await this.request(
      "PATCH",
      `/session/${part.sessionID}/message/${part.messageID}/part/${part.id}`,
      {
        ...part,
        ...updates
      }
    );
    const updated = this.unwrap(result);
    if (updated) {
      this.lastPart = updated;
      return true;
    }
    return false;
  }
  async ignorePreviousPart() {
    if (!this.lastPart) {
      return false;
    }
    const ignored = await this.updatePart(this.lastPart, { ignored: true });
    if (!ignored) {
      return false;
    }
    this.lastPart = null;
    return true;
  }
  async request(method, path, body) {
    try {
      const url = `${this.apiBaseUrl}${path}`;
      const response = await fetch(url, {
        method,
        headers: {
          "Content-Type": "application/json",
          "x-opencode-directory": this.projectDirectory
        },
        body: body ? JSON.stringify(body) : void 0
      });
      if (!response.ok) {
        console.error("[OpenCode] API request failed", {
          path,
          status: response.status
        });
        return null;
      }
      const json = await response.json().catch(() => null);
      return json;
    } catch (error) {
      console.error("[OpenCode] API request error", error);
      return null;
    }
  }
  unwrap(result) {
    if (!result) {
      return null;
    }
    if (typeof result === "object") {
      const payload = result;
      if (payload.data) {
        return payload.data;
      }
      if (payload.message) {
        return payload.message;
      }
    }
    return result;
  }
  normalizeBaseUrl(baseUrl) {
    return baseUrl.replace(/\/+$/, "");
  }
};

// src/context/ContextManager.ts
var import_obsidian5 = require("obsidian");

// src/context/WorkspaceContext.ts
var import_obsidian4 = require("obsidian");
var WorkspaceContext = class {
  constructor(app) {
    this.lastSelection = null;
    this.lastMarkdownView = null;
    this.app = app;
  }
  trackViewSelection(view) {
    var _a, _b, _c;
    if (view) {
      this.lastMarkdownView = view;
    }
    const sourcePath = (_a = view == null ? void 0 : view.file) == null ? void 0 : _a.path;
    const selection = (_c = (_b = view == null ? void 0 : view.editor) == null ? void 0 : _b.getSelection()) != null ? _c : "";
    if (sourcePath && selection.trim()) {
      this.lastSelection = {
        text: selection,
        sourcePath
      };
    }
  }
  gatherContext(maxNotes, maxSelectionLength) {
    var _a, _b, _c, _d, _e;
    const leaves = this.app.workspace.getLeavesOfType("markdown");
    const paths = /* @__PURE__ */ new Set();
    for (const leaf of leaves) {
      const view2 = leaf.view;
      const path = (_a = view2.file) == null ? void 0 : _a.path;
      if (path) {
        paths.add(path);
      }
    }
    const openNotePaths = Array.from(paths).slice(0, Math.max(0, maxNotes));
    const view = (_b = this.app.workspace.getActiveViewOfType(import_obsidian4.MarkdownView)) != null ? _b : this.lastMarkdownView;
    this.trackViewSelection(view);
    const sourcePath = (_c = view == null ? void 0 : view.file) == null ? void 0 : _c.path;
    const selection = (_e = (_d = view == null ? void 0 : view.editor) == null ? void 0 : _d.getSelection()) != null ? _e : "";
    let selectionContext = null;
    if (sourcePath && selection.trim()) {
      selectionContext = {
        text: selection,
        sourcePath
      };
      this.lastSelection = selectionContext;
    } else if (this.lastSelection) {
      selectionContext = this.lastSelection;
    }
    if (selectionContext && selectionContext.text.length > maxSelectionLength) {
      selectionContext = {
        ...selectionContext,
        text: selectionContext.text.slice(0, maxSelectionLength) + "... [truncated]"
      };
    }
    let contextText = null;
    if (openNotePaths.length > 0 || selectionContext) {
      const lines = ["<obsidian-context>"];
      if (openNotePaths.length > 0) {
        lines.push("Currently open notes in Obsidian:");
        for (const path of openNotePaths) {
          lines.push(`- ${path}`);
        }
      }
      if (selectionContext) {
        lines.push("");
        lines.push(`Selected text (from ${selectionContext.sourcePath}):`);
        lines.push('"""');
        lines.push(selectionContext.text);
        lines.push('"""');
      }
      lines.push("</obsidian-context>");
      contextText = lines.join("\n");
    }
    return {
      openNotePaths,
      selection: selectionContext,
      contextText
    };
  }
};

// src/context/ContextManager.ts
var ContextManager = class {
  constructor(deps) {
    this.contextEventRefs = [];
    this.contextRefreshTimer = null;
    this.app = deps.app;
    this.settings = deps.settings;
    this.client = deps.client;
    this.workspaceContext = new WorkspaceContext(this.app);
    this.getServerState = deps.getServerState;
    this.getCachedIframeUrl = deps.getCachedIframeUrl;
    this.setCachedIframeUrl = deps.setCachedIframeUrl;
    this.registerEvent = deps.registerEvent;
  }
  updateSettings(settings) {
    this.settings = settings;
    this.updateListeners();
  }
  updateListeners() {
    if (!this.settings.injectWorkspaceContext) {
      this.clearListeners();
      return;
    }
    if (this.contextEventRefs.length > 0) {
      return;
    }
    const activeLeafRef = this.app.workspace.on("active-leaf-change", (leaf) => {
      if ((leaf == null ? void 0 : leaf.view) instanceof import_obsidian5.MarkdownView) {
        this.workspaceContext.trackViewSelection(leaf.view);
      }
      this.scheduleRefresh(0);
    });
    const fileOpenRef = this.app.workspace.on("file-open", () => {
      this.scheduleRefresh();
    });
    const fileCloseRef = this.app.workspace.on("file-close", () => {
      this.scheduleRefresh();
    });
    const layoutChangeRef = this.app.workspace.on("layout-change", () => {
      this.scheduleRefresh();
    });
    const editorChangeRef = this.app.workspace.on(
      "editor-change",
      (_editor, view) => {
        if (view instanceof import_obsidian5.MarkdownView) {
          this.workspaceContext.trackViewSelection(view);
        }
        this.scheduleRefresh(500);
      }
    );
    const selectionChangeRef = this.app.workspace.on(
      "editor-selection-change",
      (_editor, view) => {
        if (view instanceof import_obsidian5.MarkdownView) {
          this.workspaceContext.trackViewSelection(view);
        }
        this.scheduleRefresh(200);
      }
    );
    this.contextEventRefs = [
      activeLeafRef,
      fileOpenRef,
      fileCloseRef,
      layoutChangeRef,
      editorChangeRef,
      selectionChangeRef
    ];
    this.contextEventRefs.forEach((ref) => this.registerEvent(ref));
  }
  clearListeners() {
    for (const ref of this.contextEventRefs) {
      this.app.workspace.offref(ref);
    }
    this.contextEventRefs = [];
    if (this.contextRefreshTimer !== null) {
      window.clearTimeout(this.contextRefreshTimer);
      this.contextRefreshTimer = null;
    }
  }
  scheduleRefresh(delayMs = 300) {
    const leaf = this.getLeafForRefresh();
    if (!leaf) {
      return;
    }
    if (this.contextRefreshTimer !== null) {
      window.clearTimeout(this.contextRefreshTimer);
    }
    this.contextRefreshTimer = window.setTimeout(() => {
      this.contextRefreshTimer = null;
      void this.refreshContext(leaf);
    }, delayMs);
  }
  getLeafForRefresh() {
    const activeLeaf = this.app.workspace.activeLeaf;
    if ((activeLeaf == null ? void 0 : activeLeaf.view.getViewType()) === OPENCODE_VIEW_TYPE) {
      return activeLeaf;
    }
    return this.getVisibleSidebarLeaf();
  }
  getVisibleSidebarLeaf() {
    const leaves = this.app.workspace.getLeavesOfType(OPENCODE_VIEW_TYPE);
    if (leaves.length === 0) {
      return null;
    }
    const rightSplit = this.app.workspace.rightSplit;
    if (!rightSplit || rightSplit.collapsed) {
      return null;
    }
    const leaf = leaves[0];
    return leaf.getRoot() === rightSplit ? leaf : null;
  }
  async handleServerRunning() {
    const activeLeaf = this.app.workspace.activeLeaf;
    if ((activeLeaf == null ? void 0 : activeLeaf.view.getViewType()) === OPENCODE_VIEW_TYPE) {
      await this.refreshContext(activeLeaf);
    }
  }
  async refreshContextForView(view) {
    if (!this.settings.injectWorkspaceContext) {
      return;
    }
    const leaf = this.getLeafForRefresh();
    if (!leaf) {
      return;
    }
    await this.refreshContext(leaf);
  }
  async refreshContext(leaf) {
    var _a;
    if (!this.settings.injectWorkspaceContext) {
      return;
    }
    if (this.getServerState() !== "running") {
      return;
    }
    const view = leaf.view instanceof OpenCodeView ? leaf.view : null;
    const iframeUrl = (_a = this.getCachedIframeUrl()) != null ? _a : view == null ? void 0 : view.getIframeUrl();
    if (!iframeUrl) {
      return;
    }
    const sessionId = this.client.resolveSessionId(iframeUrl);
    if (!sessionId) {
      return;
    }
    this.setCachedIframeUrl(iframeUrl);
    const { contextText } = this.workspaceContext.gatherContext(
      this.settings.maxNotesInContext,
      this.settings.maxSelectionLength
    );
    await this.client.updateContext({
      sessionId,
      contextText
    });
  }
  destroy() {
    this.clearListeners();
  }
};

// src/main.ts
var OpenCodePlugin = class extends import_obsidian6.Plugin {
  constructor() {
    super(...arguments);
    this.settings = DEFAULT_SETTINGS;
    this.stateChangeCallbacks = [];
    this.cachedIframeUrl = null;
    this.lastBaseUrl = null;
  }
  async onload() {
    console.log("Loading OpenCode plugin");
    registerOpenCodeIcons();
    await this.loadSettings();
    await this.attemptAutodetect();
    const projectDirectory = this.getProjectDirectory();
    this.processManager = new ServerManager(this.settings, projectDirectory);
    this.processManager.on("stateChange", (state) => {
      this.notifyStateChange(state);
    });
    this.processManager.on("projectDirectoryChanged", async (newDirectory) => {
      this.settings.projectDirectory = newDirectory;
      await this.saveData(this.settings);
      this.refreshClientState();
      if (this.getServerState() === "running") {
        await this.stopServer();
        await this.startServer();
      }
    });
    this.openCodeClient = new OpenCodeClient(
      this.getApiBaseUrl(),
      this.getServerUrl(),
      projectDirectory
    );
    this.lastBaseUrl = this.getServerUrl();
    this.contextManager = new ContextManager({
      app: this.app,
      settings: this.settings,
      client: this.openCodeClient,
      getServerState: () => this.getServerState(),
      getCachedIframeUrl: () => this.cachedIframeUrl,
      setCachedIframeUrl: (url) => {
        this.cachedIframeUrl = url;
      },
      registerEvent: (ref) => this.registerEvent(ref)
    });
    this.viewManager = new ViewManager({
      app: this.app,
      settings: this.settings,
      client: this.openCodeClient,
      contextManager: this.contextManager,
      getCachedIframeUrl: () => this.cachedIframeUrl,
      setCachedIframeUrl: (url) => {
        this.cachedIframeUrl = url;
      },
      getServerState: () => this.getServerState()
    });
    console.log(
      "[OpenCode] Configured with project directory:",
      projectDirectory
    );
    this.registerView(
      OPENCODE_VIEW_TYPE,
      (leaf) => new OpenCodeView(leaf, this)
    );
    this.addSettingTab(new OpenCodeSettingTab(
      this.app,
      this,
      this.settings,
      this.processManager,
      () => this.saveSettings()
    ));
    this.addRibbonIcon(OPENCODE_ICON_NAME, "OpenCode", () => {
      void this.viewManager.activateView();
    });
    this.addCommand({
      id: "toggle-opencode-view",
      name: "Toggle OpenCode panel",
      callback: () => {
        void this.viewManager.toggleView();
      },
      hotkeys: [
        {
          modifiers: ["Mod", "Shift"],
          key: "o"
        }
      ]
    });
    this.addCommand({
      id: "start-opencode-server",
      name: "Start OpenCode server",
      callback: () => {
        this.startServer();
      }
    });
    this.addCommand({
      id: "stop-opencode-server",
      name: "Stop OpenCode server",
      callback: () => {
        this.stopServer();
      }
    });
    if (this.settings.autoStart) {
      this.app.workspace.onLayoutReady(async () => {
        await this.startServer();
      });
    }
    this.contextManager.updateSettings(this.settings);
    this.processManager.on("stateChange", (state) => {
      if (state === "running") {
        void this.contextManager.handleServerRunning();
      }
    });
    this.registerCleanupHandlers();
    console.log("OpenCode plugin loaded");
  }
  async onunload() {
    this.contextManager.destroy();
    await this.stopServer();
    this.app.workspace.detachLeavesOfType(OPENCODE_VIEW_TYPE);
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  /**
   * Attempt to autodetect opencode executable on startup
   * Triggers when opencodePath is empty and useCustomCommand is false
   */
  async attemptAutodetect() {
    if (this.settings.opencodePath || this.settings.useCustomCommand) {
      return;
    }
    console.log("[OpenCode] Attempting to autodetect opencode executable...");
    const detectedPath = ExecutableResolver.resolve("opencode");
    if (detectedPath && detectedPath !== "opencode") {
      console.log("[OpenCode] Autodetected opencode at:", detectedPath);
      this.settings.opencodePath = detectedPath;
      await this.saveData(this.settings);
      new import_obsidian6.Notice(`OpenCode executable found at ${detectedPath}`);
    } else {
      console.log("[OpenCode] Could not autodetect opencode executable");
      new import_obsidian6.Notice("Could not find opencode. Please check Settings");
    }
  }
  async saveSettings() {
    await this.saveData(this.settings);
    this.processManager.updateSettings(this.settings);
    this.refreshClientState();
    this.contextManager.updateSettings(this.settings);
    this.viewManager.updateSettings(this.settings);
  }
  async startServer() {
    const success = await this.processManager.start();
    if (success) {
      new import_obsidian6.Notice("OpenCode server started");
    } else {
      const error = this.processManager.getLastError();
      if (error) {
        new import_obsidian6.Notice(`OpenCode failed to start: ${error}`, 1e4);
      } else {
        new import_obsidian6.Notice("OpenCode failed to start. Check Settings for details.", 5e3);
      }
    }
    return success;
  }
  async stopServer() {
    await this.processManager.stop();
    new import_obsidian6.Notice("OpenCode server stopped");
  }
  getServerState() {
    var _a;
    return (_a = this.processManager.getState()) != null ? _a : "stopped";
  }
  getLastError() {
    var _a;
    return (_a = this.processManager.getLastError()) != null ? _a : null;
  }
  getServerUrl() {
    return this.processManager.getUrl();
  }
  getApiBaseUrl() {
    return `http://${this.settings.hostname}:${this.settings.port}`;
  }
  getStoredIframeUrl() {
    return this.cachedIframeUrl;
  }
  setCachedIframeUrl(url) {
    this.cachedIframeUrl = url;
  }
  onServerStateChange(callback) {
    this.stateChangeCallbacks.push(callback);
    return () => {
      const index = this.stateChangeCallbacks.indexOf(callback);
      if (index > -1) {
        this.stateChangeCallbacks.splice(index, 1);
      }
    };
  }
  notifyStateChange(state) {
    for (const callback of this.stateChangeCallbacks) {
      callback(state);
    }
  }
  refreshClientState() {
    const nextUiBaseUrl = this.getServerUrl();
    const nextApiBaseUrl = this.getApiBaseUrl();
    const projectDirectory = this.getProjectDirectory();
    this.openCodeClient.updateBaseUrl(nextApiBaseUrl, nextUiBaseUrl, projectDirectory);
    if (this.lastBaseUrl && this.lastBaseUrl !== nextUiBaseUrl) {
      this.cachedIframeUrl = null;
    }
    this.lastBaseUrl = nextUiBaseUrl;
  }
  refreshContextForView(view) {
    void this.contextManager.refreshContextForView(view);
  }
  async ensureSessionUrl(view) {
    await this.viewManager.ensureSessionUrl(view);
  }
  getProjectDirectory() {
    if (this.settings.projectDirectory) {
      console.log("[OpenCode] Using project directory from settings:", this.settings.projectDirectory);
      return this.settings.projectDirectory;
    }
    const adapter = this.app.vault.adapter;
    const vaultPath = adapter.basePath || "";
    if (!vaultPath) {
      console.warn("[OpenCode] Warning: Could not determine vault path");
    }
    console.log("[OpenCode] Using vault path as project directory:", vaultPath);
    return vaultPath;
  }
  registerCleanupHandlers() {
    this.registerEvent(
      this.app.workspace.on("quit", () => {
        console.log("[OpenCode] Obsidian quitting - performing sync cleanup");
        this.stopServer();
      })
    );
  }
};
